name: pihole

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:8080/tcp"
      - "443:443/tcp"
    environment:
      TZ: "America/Los_Angeles"
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_dns_rateLimit_count: 0
      FTLCONF_dns_rateLimit_interval: 0
      FTLCONF_dns_specialDomains_iCloudPrivateRelay: "false"
    volumes:
      - 'etc-pihole:/etc/pihole'
      - 'etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped

volumes:
  etc-pihole:
  etc-dnsmasq.d:
