version: "3"

name: pihole

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: "host"
    environment:
      TZ: "America/Los_Angeles"
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      DNSMASQ_LISTENING: "all"
    volumes:
      - 'etc-pihole:/etc/pihole'
      - 'etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped

volumes:
  etc-pihole:
  etc-dnsmasq.d:
